version: '3.9'
services:
  server: 
    container_name: Twit-server
    hostname: server
    image: ghcr.io/harshasomisetty/twit_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - app-net
      
  frontend:
    container_name: Twit-frontend
    hostname: frontend
    image: ghcr.io/harshasomisetty/twit_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - app-net

networks:
  app-net:
