version: '3.9'
services:
  server: 
    container_name: Twit-server
    image: ghcr.io/harshasomisetty/twit_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-net
    mem_limit: 50m
    environment:
      - MONGO_URI=$MONGO_URI
  
  frontend:
    container_name: Twit-frontend
    image: ghcr.io/harshasomisetty/twit_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-net
    mem_limit: 50m
    profiles:
      - donotstart
networks:
  app-net:
