version: '3.9'
services:
  server: 
    container_name: Twit-server
    # image: ghcr.io/harshasomisetty/twit_server
    image: twitcontainer.azurecr.io/twit_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-net

  frontend:
    container_name: Twit-frontend
    # image: ghcr.io/harshasomisetty/twit_frontend
    image: twitcontainer.azurecr.io/twit_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-net

volumes:
  esdata:

networks:
  app-net:
