version: '3.9'
services:
  server: 
    container_name: Twit-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app/data
    networks:
      - app-net

  frontend:
    container_name: Twit-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-net

volumes:
  esdata:

networks:
  app-net:
